<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ElFinder\Module'                                => __DIR__ . '/Module.php',
  'ElFinder\Controller\IndexController'            => __DIR__ . '/src/ElFinder/Controller/IndexController.php',
  'ElFinder\Exception\ExceptionInterface'          => __DIR__ . '/src/ElFinder/Exception/ExceptionInterface.php',
  'ElFinder\Exception\InvalidArgumentException'    => __DIR__ . '/src/ElFinder/Exception/InvalidArgumentException.php',
  'ElFinder\Exception\LanguageNotFoundException'   => __DIR__ . '/src/ElFinder/Exception/LanguageNotFoundException.php',
  'ElFinder\Exception\PluginDataNotFoundException' => __DIR__ . '/src/ElFinder/Exception/PluginDataNotFoundException.php',
  'ElFinder\Exception\RuntimeException'            => __DIR__ . '/src/ElFinder/Exception/RuntimeException.php',
  'ElFinder\Exception\SiteNotFoundException'       => __DIR__ . '/src/ElFinder/Exception/SiteNotFoundException.php',
  'elFinder'                                       => __DIR__ . '/src/ElFinder/Model/elFinder.class.php',
  'elFinderConnector'                              => __DIR__ . '/src/ElFinder/Model/elFinderConnector.class.php',
  'elFinderVolumeDriver'                           => __DIR__ . '/src/ElFinder/Model/elFinderVolumeDriver.class.php',
  'elFinderVolumeFTP'                              => __DIR__ . '/src/ElFinder/Model/elFinderVolumeFTP.class.php',
  'elFinderVolumeLocalFileSystem'                  => __DIR__ . '/src/ElFinder/Model/elFinderVolumeLocalFileSystem.class.php',
  'elFinderVolumeMySQL'                            => __DIR__ . '/src/ElFinder/Model/elFinderVolumeMySQL.class.php',
);
