<?= $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?=
    $this->headTitle('ElFinder')->setSeparator(' - ')->setAutoEscape(
        false
    ) ?>

    <?=
    $this->headMeta()->appendName(
        'viewport',
        'width=device-width, initial-scale=1.0'
    ) ?>

    <!-- Le styles -->
    <?= $this->headLink(); ?>

    <!-- Scripts -->
    <?= $this->headScript(); ?>

</head>
<body>
<div class="container">
    <?= $this->content; ?>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
