<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ElFinder')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(); ?>

    <!-- Scripts -->
    <?php echo $this->headScript(); ?>

</head>
<body>
<div class="container">
    <?php echo $this->content; ?>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
