<?php

/**
 * ElFinder Includes
 */

/*   Google Jquery if needed */

if (!empty($this->useGoogleJquery) && $this->useGoogleJquery === true) {
    $this->headScript()->appendFile(
        '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js',
        'text/javascript'
    );

    $this->headScript()->appendFile(
        '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js',
        'text/javascript'
    );

    $this->headLink()->appendStylesheet(
        '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css'
    );
}

$this->headScript()->appendFile(
    '/modules/el-finder/js/elfinder.full.js',
    'text/javascript'
);

$this->headLink()->appendStylesheet(
   '/modules/el-finder/css/elfinder.full.css'
);

//$this->headLink()->appendStylesheet(
//    $this->basePath() . $this->elPublicPath . '/css/theme.css'
//);

