<?php
include 'common.phtml';
?>

<script type="text/javascript">
    $(function(){
        var elf = $('#elfinder').elfinder({
            // lang: 'ru',             // language (OPTIONAL)
            url : '<?php echo $this->connectorPath; ?>',  // connector URL (REQUIRED)
            getFileCallback : function(fileInfo) {
                window.opener.elFinderFileSelected(fileInfo['url']);
                window.close();
            },
            resizable: false
        }).elfinder('instance');
    });
</script>

<div id="elfinder"></div>

