<?php
include 'common.phtml';
?>

<script type="text/javascript">
    $(function(){

        var $window = $(window);
        var init_win_height = $window.height() - 20;

        var thisElFinder = $('#elfinder').elfinder({
            url : '<?=  $this->connectorPath; ?>',
            height: init_win_height
        });

        var elf = thisElFinder.elfinder('instance');

        var $window = $(window);
        $window.resize(function(){
            var win_height = $window.height();
            if( thisElFinder.height() != win_height ){
                thisElFinder.height(win_height).resize();
            }
        });
    });
</script>

<div id="elfinder"></div>

