<?php include 'common.phtml'; ?>

<?php $this->headScript()->captureStart() ?>
$(function () {

    var $window = jQuery(window);
    var init_win_height = $window.height() - 20;

    var thisElFinder = $('#elfinder').elfinder({
        url: '<?=  $this->connectorPath; ?>',
        height: init_win_height
    });

    var elf = thisElFinder.elfinder('instance');
    $window.resize(function () {
        var win_height = $window.height() - 20;
        if (thisElFinder.height() != win_height) {
            thisElFinder.height(win_height).resize();
        }
    });
});
<?php $this->headScript()->captureEnd() ?>

<div id="elfinder"></div>

