<?php
include 'common.phtml';
?>

<script type="text/javascript">

    function getUrlParam(paramName) {
        var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i');
        var match = window.location.search.match(reParam);

        return (match && match.length > 1) ? match[1] : '';
    }

    $(function () {

        var $window = $(window);
        var init_win_height = $window.height() - 20;

        var thisElFinder = $('#elfinder').elfinder({
            url: '<?=  $this->connectorPath; ?>',

            getFileCallback: function (fileInfo) {
                parent.tinymce.activeEditor.windowManager.getParams().setUrl(fileInfo['url']);
                parent.tinymce.activeEditor.windowManager.close();
            },
            resizable: false,
            height: init_win_height
        });

        var elf = thisElFinder.elfinder('instance');

        var $window = $(window);
        $window.resize(function () {
            var win_height = $window.height() - 20;
            if (thisElFinder.height() != win_height) {
                thisElFinder.height(win_height).resize();
            }
        });

    });
</script>

<div id="elfinder"></div>

